---
apiVersion: v1
kind: Service
metadata:
  name: service-pastry-mock
  namespace: service-pastry
  labels:
    app: service-pastry-mock
    subsystem: app
spec:
  ports:
    - name: https
      port: 5000
  selector:
    app: service-pastry-mock
    subsystem: app
  type: ClusterIP